sonar.projectKey=asd-entrega_asd-entrega
sonar.organization=asd-entrega
sonar.projectName=ASD-Entrega
sonar.branch.name=main

sonar.sources=backend
sonar.exclusions=backend/tests/**
sonar.tests=backend/tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.host.url=https://sonarcloud.io
